package com.mvalu.bettr_api.network

enum class ApiTag {
    GENERATE_ACCESS_TOKEN_API,
    GET_USER_API,
    UPDATE_USER_API,
    HOME_MODULE_API,
    STATEMENT_TRANSACTIONS_API,
    ACCOUNT_STATEMENTS_API,
    ACCOUNT_STATEMENT_TRANSACTIONS_API,
    ACCOUNT_STATEMENT_TRANSACTIONS_INFO_API,
    UPDATE_LEAD_API,
    VALIDATE_PAN_API,
    VALIDATE_PINCODE_API,
    BUREAU_STATUS_API,
    BUREAU_QUESTION_API,
    BUREAU_ANSWER_API,
    ID_PROOF_UPLOAD_API,
    AADHAR_FRONT_UPLOAD_API,
    AADHAR_BACK_UPLOAD_API,
    PAN_UPLOAD_API,
    ADDRESS_PROOF_UPLOAD_API,
    BANK_STATEMENT_UPLOAD_API,
    SALARY_SLIP_UPLOAD_API,
    PROFILE_PIC_UPLOAD_API
}