package com.mvalu.bettr_api.network

enum class ApiTag {
    GENERATE_ACCESS_TOKEN_API,
    GET_USER_API,
    UPDATE_USER_API,
    HOME_MODULE_API,
    STATEMENT_TRANSACTIONS_API,
    ACCOUNT_STATEMENTS_API,
    ACCOUNT_STATEMENT_TRANSACTIONS_API,
    ACCOUNT_STATEMENT_TRANSACTIONS_INFO_API,
    UPDATE_LEAD_API,
    VALIDATE_PAN_API
}